# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_relationmentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dropout_prob',
            field=models.FloatField(default=0.0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
